version: "3"
services:
  movement-db:
    build: ./database
    container_name: movement-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=movement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  movement-backend:
    build: ./animal-movement-backend
    container_name: backend
    environment:
      - DB_SERVER=movement-db
      - POSTGRES_DB=jdbc:postgresql://movement-db/movement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 8080:8080
    depends_on:
      - movement-db

  movement-frontend:
    build: ./animal-movement-frontend
    container_name: movement-frontend
    ports:
      - 3000:3000
    depends_on:
      - movement-backend
    links:
      - movement-backend
